import Link from "next/link";
import { DemoPlayer } from "./DemoPlayer";

export const metadata = {
  title: "RevSlot — Live Demo",
  description:
    "See AI product placement in action. This precomputed demo shows a McDonald's placement generated by RevSlot's AI Director pipeline.",
};

/*
 * /demo — Public, no-auth page
 *
 * Shows a precomputed AI placement result in the VibePlayer so judges
 * (or anyone) can see the end product instantly, even if the live
 * pipeline is unavailable due to cold starts or API rate limits.
 */
export default function DemoPage() {
  return (
    <main className="min-h-screen bg-[#fffeec] px-6 py-14 text-black">
      <div className="mx-auto flex w-full max-w-4xl flex-col gap-8">
        {/* Header */}
        <header className="text-center">
          <span className="mb-4 inline-block rounded-full border border-[#36A64F]/30 bg-[#36A64F]/10 px-4 py-1 font-['Space_Mono'] text-xs font-bold uppercase tracking-widest text-[#36A64F]">
            LIVE DEMO
          </span>
          <h1 className="font-['Space_Grotesk'] text-3xl font-bold tracking-tight">
            AI Product Placement in Action
          </h1>
          <p className="mt-3 text-sm text-black/50" style={{ fontFamily: "'Inter', sans-serif" }}>
            This is a real result from RevSlot&apos;s AI Director pipeline. The original Friends clip
            was analyzed by GPT-4o Vision, which chose the best frame for a McDonald&apos;s placement.
            Flux Kontext Max composited the product into the scene, and Kling Video animated a 5-second
            AI clip. The VibePlayer below splices everything together with a shoppable overlay.
          </p>
        </header>

        {/* Player */}
        <DemoPlayer />

        {/* Pipeline breakdown */}
        <section className="rounded-2xl border border-black/10 bg-white/60 p-6 space-y-3">
          <h2 className="font-['Space_Grotesk'] text-lg font-semibold">What happened behind the scenes</h2>
          <ol className="list-decimal list-inside space-y-2 text-sm text-black/70" style={{ fontFamily: "'Inter', sans-serif" }}>
            <li>
              <strong>Frame sampling</strong> — 12 frames were extracted across the video for analysis.
            </li>
            <li>
              <strong>AI Director (GPT-4o Vision)</strong> — Analyzed all frames, selected timestamp 1.4s as the best moment,
              and wrote product-type-aware compositing instructions for a McDonald&apos;s placement.
            </li>
            <li>
              <strong>Flux Kontext Max</strong> — Regenerated the chosen frame with the product naturally integrated
              (correct perspective, lighting, shadows). Not pasted, generated from scratch.
            </li>
            <li>
              <strong>Kling Video</strong> — Animated the composited frame into a seamless 5-second clip.
            </li>
            <li>
              <strong>VibePlayer</strong> — Spliced the AI clip into the original video with a shoppable buy-now bubble.
            </li>
          </ol>
        </section>

        {/* Pipeline steps */}
        <div className="rounded-xl border border-black/10 bg-white/60 p-4">
          <p className="text-xs font-['Space_Mono'] uppercase tracking-wider text-black/40 mb-2">Pipeline steps</p>
          <div className="flex flex-wrap gap-2">
            {[
              "reference-image-analyzed",
              "director-decided",
              "ai-placement-done",
              "frame-persisted",
              "video-generated",
              "video-persisted",
            ].map((step) => (
              <span
                key={step}
                className="text-xs px-2.5 py-1 rounded-full bg-[#36A64F]/10 text-[#36A64F]"
              >
                {step}
              </span>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div className="text-center space-y-3">
          <Link
            href="/sign-up"
            className="inline-block rounded-lg bg-[#36A64F] px-7 py-3 font-['Space_Mono'] text-sm font-bold uppercase tracking-wider text-white transition hover:bg-[#36A64F]/90"
          >
            Try It Yourself
          </Link>
          <p className="text-xs text-black/30 font-['Space_Mono'] uppercase tracking-widest">
            No credit card required
          </p>
        </div>
      </div>
    </main>
  );
}
